version: '3.9'

services:
  node:
    container_name: 'kae'
    image: 'node:18.0.0-alpine'
    working_dir: '/var/www/html'
    volumes:
      - ./:/var/www/html/
    network_mode: 'host'
    stdin_open: true
